### ISSUE TITLE
Is there a way to turn off logging to the console when translating?

### ISSUE THREAD

**Issue by sandaruonline** [mohan-cao/owoify-js#1]

**Comment by mohan-cao** [comment]
oh hi uhhhh yes

**Comment by mohan-cao** [comment]
My bad, forgot to productionise my code (didn't think people were gonna actually use it lol)

In the meantime (if you don't want to bump versions), you could always redirect console output by setting console.debug to your own function. I can't imagine this will be very helpful for 
e.g.
`console.debug = function(){ /*custom logger implementation*/ }`

**Comment by mohan-cao** [comment]
Fixed in v1.0.7

**Comment by sandaruonline** [comment]
Thank you so much!
